### ISSUE TITLE
Option for other selectors than ID's

### ISSUE THREAD

**Issue by vdrnn** [metafizzy/flickity-hash#1]
I have the issue now, that the slider is placed somewhere at the bottom of a long page. When I link to the slider with the hash, the site jumps to that anchor. But I want the user to stay at the top but still select the correct slide of course. 

Is it possible to use a different selector, like a custom data attribute additionally to the ID? For example: 

`<div class="carousel-cell" data-hash="carousel-cell1">...</div>`

Or is there another way of preventing the user to jump to the bottom of the anchor when coming from another page?

**Comment by desandro** [comment]
Thanks for reporting this issue!

> When I link to the slider with the hash, the site jumps to that anchor. 

This is default browser behavior. This behavior would still happen even with Flickity disabled.

One solution is to remove `id`s from cell elements, and use [`selectCell`](https://flickity.metafizzy.co/api.html#selectcell) to select a matching cell.  See demo https://s.codepen.io/desandro/debug/zWRGEZ#carousel-cell2

``` js
var flkty = new Flickity('.carousel');

if ( location.hash ) {
  var hash = location.hash.slice(1);
  console.log( hash );
  flkty.selectCell( '[data-id="' + hash + '"]' );
}
```

This replicates only being able to link to a cell. `flickity-hash` also enables clicking links to cells, and changing the URL with selected cell.

**Comment by vdrnn** [comment]
Thanks for the quick reply. 

I understand that this is a default browser behavior. That's why I was thinking to replace the id's entirely as you suggested. 

But I do also need the functionality of flickity-hash too, like changing the URL while sliding through. 

Would that be possible to achieve with the API? Right now I don't see any option in the API to set the hash?

**Comment by desandro** [comment]
Sorry, this is not possible with `flickity-hash`. 

Another solution is to reset scroll position in JavaScript

``` js
window.scrollTo( 0, 0 );
```

**Comment by vdrnn** [comment]
Thanks @desandro ! I solved it that way :)
