### ISSUE TITLE
Use hyphens instead of %20 in URL

### ISSUE THREAD

**Issue by differenceclouds** [metafizzy/flickity-hash#4]
Thank you for this feature!! One issue: the urls start looking kinda messy if the Alt text has any spaces in it. (I am loading the alt text from user generated image title in CMS) Underscores or hyphens would be preferable to "%20"

**Comment by differenceclouds** [comment]
Hm I'm realizing this change might make more problems for myself when actually trying to link to individual images from another page....

**Comment by differenceclouds** [comment]
I'm using this as a solution: https://stackoverflow.com/questions/28977793/convert-spaces-to-dash-and-lowercase-with-php
```
<?php print (str_replace(' ', '-', strtolower($blob))); ?>
```

**Comment by desandro** [comment]
Hello! Its up to you to provide whatever string you want to use for `id`. A simpler solution might be to use numbers for any carousel cell, across all carousel instances. `cell1, cell2, cell3 ...`.

**Comment by differenceclouds** [comment]
Ah, but you see, I need meaningful SEMANTICS! Thanks for the reply.
