### ISSUE TITLE
Linking to carousel-cell with php from remote page

### ISSUE THREAD

**Issue by PietM** [metafizzy/flickity-hash#5]
The hash option for Flickity is excellent. I'm wondering if there is a way to number the carousel-cell via php and link from a separate template. Would it look something like (?):

```
<ul>
<?php
$i = 1;
while(get_sub_field('images')):
echo '<li><a href="' . get_permalink() . '/carousel-cell' . $i . '">' . get_sub_field('images') . '</a></li>' ;
$i++;
endwhile; ?>
</ul>

```

**Comment by desandro** [comment]
@PietM You would set `href` to match the element's IDs. So if you have

``` html
<div class="carousel">
  <div class="carousel-cell" id="carousel-cell1"></div>
  <div class="carousel-cell" id="carousel-cell2"></div>
  <div class="carousel-cell" id="carousel-cell3"></div>
</div>
```
Then your links external page links would look like:

``` html
<a href="page-name#carousel-cell1">View cell 1</a>
```

**Comment by PietM** [comment]
Thanks for the response! Flickity is truly indispensable.

I'm trying to better understand how I assign the id value "carousel-cell1", "carousel-cell2" via php, so the link opens a separate page with the specific cell in view. 

Not sure this is possible. My code above doesn't work. 

Would appreciate any additional assistance. 
Thank you!

**Comment by desandro** [comment]
Sorry, I'm not well-versed in PHP so you'll have to find you're own solution.
